### ISSUE TITLE
Show the Resin.io logo on the footer

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-etcher#68]

**Comment by taahirisaacs** [comment]
This way should work @jviotti 

![screen shot 2016-01-18 at 9 56 49 am](https://cloud.githubusercontent.com/assets/15251376/12385957/d2ef42aa-bdc9-11e5-97f1-9d68cee039f9.png)

**Comment by jviotti** [comment]
@taahirisaacs Looks great! Can you share with me an SVG of the Resin.io logo + text? Also, one observation:

- The footer text currently says "An open source project by Resin.io", but the while thing looks to texty this way. What do you think? cc @alexandrosm

**Comment by jviotti** [comment]
It probably will look decent enough. The logo colour and bigger font should balance the text:

![screenshot 2016-01-18 09 53 33](https://cloud.githubusercontent.com/assets/2192773/12393018/6c85a734-bdc9-11e5-852e-1f9d1ac5a712.png)

**Comment by taahirisaacs** [comment]
@jviotti here you go
[logo-right.svg.zip](https://github.com/resin-io/resin-etcher/files/94460/logo-right.svg.zip)
